"""System commands: date, env, whoami, uname, timeout, kill, sleep, ..."""

from __future__ import annotations

from ._core import (
    command_arch,
    command_chcon,
    command_chroot,
    command_coreutils,
    command_date,
    command_env,
    command_expr,
    command_factor,
    command_false,
    command_groups,
    command_hostid,
    command_hostname,
    command_id,
    command_kill,
    command_logname,
    command_nice,
    command_nohup,
    command_nproc,
    command_pathchk,
    command_pinky,
    command_printenv,
    command_runcon,
    command_sleep,
    command_stdbuf,
    command_stty,
    command_timeout,
    command_true,
    command_tty,
    command_uname,
    command_uptime,
    command_users,
    command_who,
    command_whoami,
)

__all__ = [
    "command_arch",
    "command_chcon",
    "command_chroot",
    "command_coreutils",
    "command_date",
    "command_env",
    "command_expr",
    "command_factor",
    "command_false",
    "command_groups",
    "command_hostid",
    "command_hostname",
    "command_id",
    "command_kill",
    "command_logname",
    "command_nice",
    "command_nohup",
    "command_nproc",
    "command_pathchk",
    "command_pinky",
    "command_printenv",
    "command_runcon",
    "command_sleep",
    "command_stdbuf",
    "command_stty",
    "command_timeout",
    "command_true",
    "command_tty",
    "command_uname",
    "command_uptime",
    "command_users",
    "command_who",
    "command_whoami",
]
