"""File-system commands: ls, stat, cat, head, tail, wc, cp, mv, rm, mkdir, chmod, ..."""

from __future__ import annotations

from ._core import (
    command_basename,
    command_bracket,
    command_cat,
    command_chgrp,
    command_chmod,
    command_chown,
    command_cksum,
    command_cp,
    command_dd,
    command_df,
    command_dir,
    command_dirname,
    command_du,
    command_hash,
    command_head,
    command_install,
    command_link,
    command_ln,
    command_ls,
    command_mkdir,
    command_mkfifo,
    command_mknod,
    command_mktemp,
    command_mv,
    command_pwd,
    command_readlink,
    command_realpath,
    command_rm,
    command_rmdir,
    command_shred,
    command_stat,
    command_sum,
    command_sync,
    command_tail,
    command_tee,
    command_test,
    command_touch,
    command_truncate,
    command_unlink,
    command_vdir,
    command_wc,
)

__all__ = ['command_basename', 'command_bracket', 'command_cat', 'command_chgrp', 'command_chmod', 'command_chown', 'command_cksum', 'command_cp', 'command_dd', 'command_df', 'command_dir', 'command_dirname', 'command_du', 'command_hash', 'command_head', 'command_install', 'command_link', 'command_ln', 'command_ls', 'command_mkdir', 'command_mkfifo', 'command_mknod', 'command_mktemp', 'command_mv', 'command_pwd', 'command_readlink', 'command_realpath', 'command_rm', 'command_rmdir', 'command_shred', 'command_stat', 'command_sum', 'command_sync', 'command_tail', 'command_tee', 'command_test', 'command_touch', 'command_truncate', 'command_unlink', 'command_vdir', 'command_wc']
